language: generic
before_install:
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
  - sudo apt-get update -qq
  - sudo apt-get install -y ghc leiningen
script:
  - cd java/brainfrack; mvn package
  - cd clojure/brainfrack; lein compile
  - cd haskell; ghc Brainfrack.hs
  - cd c; make

  - sudo apt-get install -y llvm-3.5 llvm-3.5-dev llvm-3.5-runtime libllvm3.5
  - cd llvm; make
