language: rust
rust:
  - stable
  - beta
  - nightly

install:
 - sudo sh -c "echo 'deb http://archive.ubuntu.com/ubuntu/ precise-proposed restricted main multiverse universe' >> /etc/apt/sources.list"

# based on instructions at http://llvm.org/apt/
 - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
 - sudo sh -c "echo 'deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
 - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main' >> /etc/apt/sources.list"
 - sudo sh -c "echo 'deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main' >> /etc/apt/sources.list"
 - sudo sh -c "echo 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main' >> /etc/apt/sources.list"
 - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
 - sudo apt-get update
 - sudo apt-get install -y --force-yes libllvm3.7 llvm-3.7 llvm-3.7-dev llvm-3.7-runtime

 - llvm-config --version
 - dpkg -S `which llvm-config` || true

# based on http://askubuntu.com/a/309787
 - sudo ln -s /usr/bin/llvm-config-3.7 /usr/local/bin/llvm-config
 - which llvm-config
 - hash -r
 - llvm-config --version

 - sudo rm -f /usr/local/clang-3.4/bin/llvm-config
 - hash -r
 - llvm-config --version

notifications:
  email: false
