language: cpp
before_install:
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
  - sudo apt-get update -qq
  - sudo apt-get install -y llvm-3.5 llvm-3.5-dev
script:
  - make
notifications:
  email: false
