language: rust
rust: beta

install:
 - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
 - sudo apt-get update
 - sudo apt-get install llvm

notifications:
  email: false
