language: rust
rust:
  - stable
  - beta
  - nightly

# Install travis-cargo.
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# Install LLVM.
install:
 - sudo sh -c "echo 'deb http://archive.ubuntu.com/ubuntu/ precise-proposed restricted main multiverse universe' >> /etc/apt/sources.list"

# based on instructions at http://llvm.org/apt/
 - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
 - sudo sh -c "echo 'deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
 - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main' >> /etc/apt/sources.list"
 - sudo sh -c "echo 'deb-src http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main' >> /etc/apt/sources.list"
 - sudo sh -c "echo 'deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main' >> /etc/apt/sources.list"
 - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
 - sudo apt-get update
 - sudo apt-get install -y --force-yes libllvm3.7 llvm-3.7 llvm-3.7-dev llvm-3.7-runtime
 - sudo apt-get install libedit-dev

# llvm-config is old by default, see http://askubuntu.com/a/309787
# TODO: there must be a nicer approach
 - sudo rm -f /usr/local/clang-3.4/bin/llvm-config
 - sudo ln -s /usr/bin/llvm-config-3.7 /usr/local/bin/llvm-config
 - llvm-config --version

# Build and test.
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo doc


notifications:
  email: false

matrix:
  allow_failures:
    # These have segfault (signal 11) in the past. I could't reproduce locally, but
    # only passing on stable is sufficient.
    - rust: beta
    - rust: nightly
