[package]
name = "bfc"
version = "1.1.0"
authors = ["Wilfred Hughes <me@wilfred.me.uk>"]

[dependencies]
llvm-sys = "*"
itertools = "*"
rand = "*"
quickcheck = "*"
quickcheck_macros = "*"
tempfile = "*"
libc = "0.1"
getopts = "*"
