[package]
name = "bfc"
version = "1.2.0"
authors = ["Wilfred Hughes <me@wilfred.me.uk>"]

[dependencies]
llvm-sys = "*"
itertools = "*"
rand = "*"
quickcheck = "*"
tempfile = "*"
libc = "0.1"
getopts = "*"
matches = "*"
