[package]
name = "bfc"
version = "1.5.0"
authors = ["Wilfred Hughes <me@wilfred.me.uk>"]

[dependencies]
llvm-sys = "*"
itertools = "*"
rand = "*"
quickcheck = "*"
tempfile = "*"
getopts = "*"
matches = "*"
ansi_term = "*"
