[package]
name = "bfc"
version = "0.5.0"
authors = ["Wilfred Hughes <me@wilfred.me.uk>"]

[dependencies]
llvm_sys = "0.1.3"
itertools = "*"
rand = "*"
quickcheck = "*"
quickcheck_macros = "*"
tempfile = "*"
libc = "0.1"
