[package]
name = "bfc"
version = "1.7.0"
authors = ["Wilfred Hughes <me@wilfred.me.uk>"]
homepage = "https://github.com/Wilfred/bfc"
repository = "https://github.com/Wilfred/bfc"
description = "An industrial-grade brainfuck compiler"
readme = "README.md"
license = "GPL-2.0"

[dependencies]
llvm-sys = "*"
itertools = "*"
rand = "*"
quickcheck = "*"
tempfile = "*"
getopts = "*"
matches = "*"
ansi_term = "*"
