[package]
name = "bfc"
version = "0.3.0"
authors = ["Wilfred Hughes <me@wilfred.me.uk>"]

[dependencies]
llvm_sys = "0.1.3"
itertools = "*"
tempfile = "*"
libc = "0.1"

[dev-dependencies]
quickcheck = "*"
quickcheck_macros = "*"
rand = "*"
